services:
  oltp:
    image: postgres
    environment:
      POSTGRES_DB: 'sales_oltp'
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sales_oltp --username $POSTGRES_USER"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 45s
  generator:
    build:
      context: .
      dockerfile: ./generator/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./shared:/shared
    depends_on:
      oltp:
        condition: service_healthy
  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        SUPERSET_ADMIN: $SUPERSET_ADMIN
        SUPERSET_PASSWORD: $SUPERSET_PASSWORD
        SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
        - "8088:8088"
    command:     gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    volumes:
        - ./database:/app/superset_home/db
