name: "asbhy_interview"
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: default

model-paths: ["models"]

target-path: "target"
clean-targets:
  - target
  - dbt_packages
  - logs

models:
  ashby:
    marts:
      +materialized: table
    sources:
      +materialized: table
      +tags: ["source"]
